<h1 style="font-family:Times New Roman;">Kaggle Competition</h1>

<p style="font-family:Times New Roman;"><b><font size = "4">Suhas Alur</font></b></p>

<h1 style="font-family:Times New Roman;">Loading & Pre-processing</h1>

In [1]:
# import necessary libraries and specify that graphs should be plotted inline
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm, datasets
%cd 'C:\Users\Suhas\Documents\MSBA\Semester Two\Predictive Analytics\Homework\Homework - 5\Data'

C:\Users\Suhas\Documents\MSBA\Semester Two\Predictive Analytics\Homework\Homework - 5\Data


In [2]:
# Import the train dataset
data_train = pd.read_csv('train.csv')

In [3]:
# Splitting the dataset based on attributes and target variable
X = data_train.iloc[:,0:25]
y = data_train.adopter

In [4]:
X = np.array(X)
y = np.array(y)

In [5]:
# Splitting the train data into training and testing

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [37]:
# Feature Importance
from sklearn import datasets
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier

# fit an Extra Trees model to the data
model = ExtraTreesClassifier()
model.fit(X_train, y_train)

# display the relative importance of each attribute
print(model.feature_importances_)

[ 0.05842009  0.00560829  0.05431093  0.05853635  0.05116341  0.04855876
  0.03421883  0.06479198  0.06900566  0.0406228   0.03947478  0.05699944
  0.03977114  0.05467344  0.03762078  0.02791376  0.02742831  0.06248462
  0.05075311  0.0101801   0.00647335  0.0362107   0.05798579  0.00578673
  0.00100685]


In [43]:
from sklearn.svm import LinearSVC
from sklearn.datasets import load_iris
from sklearn.cross_validation import train_test_split
svc = LinearSVC(C=0.01, penalty="l1", dual=False)

X_train_new = svc.fit_transform(X_train, y_train)
print(X_train_new.shape)

X_test_new = svc.transform(X_test)
print(X_test_new.shape)
print(svc.coef_)

C:\Users\Suhas\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


(60677L, 17L)
(26005L, 17L)
[[  7.51170388e-04   4.58571813e-03  -3.20929346e-04   9.98648393e-05
    0.00000000e+00   1.12705254e-03   1.14693996e-02   2.86745898e-07
    5.44987216e-05  -4.48150767e-06   3.42459459e-03   3.09590930e-05
    1.48865190e-04   0.00000000e+00   0.00000000e+00   4.19881421e-03
   -7.90620612e-03   2.28363605e-06  -3.47932254e-05  -1.40759988e-04
    0.00000000e+00   3.09485239e-04  -1.03370173e-04  -1.26918595e-02
    0.00000000e+00]]


C:\Users\Suhas\Anaconda2\lib\site-packages\sklearn\utils\deprecation.py:70: DeprecationWarning: Function transform is deprecated; Support to use estimators as feature selectors will be removed in version 0.19. Use SelectFromModel instead.
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\Suhas\Anaconda2\lib\site-packages\sklearn\utils\deprecation.py:70: DeprecationWarning: Function transform is deprecated; Support to use estimators as feature selectors will be removed in version 0.19. Use SelectFromModel instead.
  warnings.warn(msg, category=DeprecationWarning)


<h1 style="font-family:Times New Roman;">Gradient Boosted Trees</h1>

In [6]:
import os
mingw_path = 'C:\\Program Files\\mingw-w64\\x86_64-6.2.0-posix-seh-rt_v5-rev1\\mingw64\\bin'
os.environ['PATH'] = mingw_path + ';' + os.environ['PATH']

import xgboost as xgb

In [102]:
model = xgb.XGBClassifier(
 learning_rate =0.8,
 n_estimators=100,
 max_depth=2,
 min_child_weight=6,
 gamma=5,
 subsample=1,
 colsample_bytree=0.5,
 reg_lambda = 0.01,
 #reg_alpha=1,
 objective= 'binary:logistic',
 nthread=10,
 scale_pos_weight=1,
 seed=42)

In [114]:
model = xgb.XGBClassifier(learning_rate =0.8, n_estimators=100, max_depth=2, min_child_weight=6, gamma=5, subsample=1, colsample_bytree=0.5, reg_alpha=0.1, objective= 'binary:logistic', nthread=10, scale_pos_weight=1, seed=42)


In [115]:
#from sklearn.ensemble import AdaBoostClassifier
#clf = AdaBoostClassifier(base_estimator = model, n_estimators=100, learning_rate = 0.1, random_state = 42)

In [116]:
model = model.fit(X_train, y_train)

In [117]:
predicted = model.predict_proba(X_test)

In [118]:
from sklearn.metrics import classification_report, confusion_matrix

def drange(start, stop, step):
    while start < stop:
            yield start
            start += step


for j in drange(0.00, 1.00, 0.01):
    cutoff = j
    y_pred = list()
    for i in range(0,len(predicted[:,1])):
        if predicted[:,1][i] > cutoff:
            y_pred.append(1)
        else:
            y_pred.append(0)
    target_names = ['class 0', 'class 1']
    print "Cutoff = {}".format(cutoff)
    print(classification_report(y_test, y_pred, target_names=target_names))
    print confusion_matrix(y_test, y_pred)
    print("*********************************************************")

Cutoff = 0.0
             precision    recall  f1-score   support

    class 0       0.00      0.00      0.00     25566
    class 1       0.02      1.00      0.03       439

avg / total       0.00      0.02      0.00     26005

[[    0 25566]
 [    0   439]]
*********************************************************
Cutoff = 0.01
             precision    recall  f1-score   support

    class 0       1.00      0.55      0.71     25566
    class 1       0.03      0.88      0.06       439

avg / total       0.98      0.56      0.70     26005

[[14151 11415]
 [   51   388]]
*********************************************************
Cutoff = 0.02
             precision    recall  f1-score   support

    class 0       0.99      0.74      0.85     25566
    class 1       0.04      0.69      0.08       439

avg / total       0.98      0.74      0.83     26005

[[18848  6718]
 [  134   305]]
*********************************************************
Cutoff = 0.03
             precision    recall 

In [586]:
# Import the train dataset
data_test = pd.read_csv('test.csv')

# Taking only the required attributes
X_test = data_test.iloc[:,0:25]
X_test = np.array(X_test)

In [587]:
predicted = model.predict_proba(X_test)

In [588]:
cutoff = 0.45
y_pred = list()
for i in range(0,len(predicted[:,1])):
    if predicted[:,1][i] > cutoff:
        y_pred.append(1)
    else:
        y_pred.append(0)

In [589]:
submission = pd.DataFrame({'user_id': data_test['user_id'], 'prediction(adopter)':y_pred})
submission = submission[['user_id', 'prediction(adopter)']]
submission.to_csv("xgboost_22ndNov.csv", index=False)

<h1 style="font-family:Times New Roman;">Ensemble Method</h1>

In [462]:
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression(random_state = 9, C = 0.001 , n_jobs = -1, penalty = 'l1', class_weight = 'balanced', intercept_scaling  = 5)

In [463]:
from sklearn.ensemble import RandomForestClassifier
model2 = RandomForestClassifier(n_estimators = 100, max_depth = 10, max_features = 7, min_samples_split = 4, bootstrap = True, oob_score = True, n_jobs = -1, class_weight = 'balanced', random_state = 42)

In [464]:
import os
mingw_path = 'C:\\Program Files\\mingw-w64\\x86_64-6.2.0-posix-seh-rt_v5-rev1\\mingw64\\bin'
os.environ['PATH'] = mingw_path + ';' + os.environ['PATH']
import xgboost as xgb

model3 = xgb.XGBClassifier(
 learning_rate =0.1,
 n_estimators=100,
 max_depth=2,
 min_child_weight=8,
 gamma=5,
 subsample=1,
 colsample_bytree=0.5,
 #reg_lambda = 0.2,
 reg_alpha=0.2,
 objective= 'binary:logistic',
 nthread=10,
 scale_pos_weight=1,
 seed=42)

In [465]:
from sklearn.ensemble import GradientBoostingClassifier  #GBM algorithm
model4 = GradientBoostingClassifier(loss = 'deviance', learning_rate=0.05, min_weight_fraction_leaf = 0.1, min_samples_split=2, n_estimators=80, max_depth=20, subsample=0.1,random_state=42)

In [470]:
from sklearn.ensemble import VotingClassifier
ensemble_classifier = VotingClassifier(estimators=[('lr', model1), ('rf', model2), ('xgb', model3), ('gbc', model4)],voting='hard')#, weights = [1,1,1,2])

In [471]:
ensemble_classifier = ensemble_classifier.fit(smox, smoy)

In [473]:
predicted = ensemble_classifier.predict(X_test)

In [474]:
from sklearn.metrics import classification_report, f1_score
from sklearn.metrics import confusion_matrix
target_names = ['class 0', 'class 1']
print(classification_report(y_test, predicted, target_names=target_names))
print confusion_matrix(y_test, predicted)

             precision    recall  f1-score   support

    class 0       0.99      0.97      0.98     25566
    class 1       0.09      0.17      0.12       439

avg / total       0.97      0.96      0.96     26005

[[24810   756]
 [  365    74]]


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

def drange(start, stop, step):
    while start < stop:
            yield start
            start += step


for j in drange(0.00, 1.00, 0.01):
    cutoff = j
    y_pred = list()
    for i in range(0,len(predicted[:,1])):
        if predicted[:,1][i] > cutoff:
            y_pred.append(1)
        else:
            y_pred.append(0)
    target_names = ['class 0', 'class 1']
    print "Cutoff = {}".format(cutoff)
    print(classification_report(y_test, y_pred, target_names=target_names))
    print confusion_matrix(y_test, y_pred)
    print("*********************************************************")

In [536]:
from sklearn.ensemble import VotingClassifier
ensemble_classifier = VotingClassifier(estimators=[('lr', model1), ('rf', model2), ('xgb', model3), ('gbc', model4)],voting='soft', weights = [1,1,1,20])

In [537]:
ensemble_classifier = ensemble_classifier.fit(X_train, y_train)
predicted = ensemble_classifier.predict_proba(X_test)

In [538]:
from sklearn.metrics import classification_report, confusion_matrix

def drange(start, stop, step):
    while start < stop:
            yield start
            start += step


for j in drange(0.00, 1.00, 0.01):
    cutoff = j
    y_pred = list()
    for i in range(0,len(predicted[:,1])):
        if predicted[:,1][i] > cutoff:
            y_pred.append(1)
        else:
            y_pred.append(0)
    target_names = ['class 0', 'class 1']
    print "Cutoff = {}".format(cutoff)
    print(classification_report(y_test, y_pred, target_names=target_names))
    print confusion_matrix(y_test, y_pred)
    print("*********************************************************")

Cutoff = 0.0
             precision    recall  f1-score   support

    class 0       0.00      0.00      0.00     25566
    class 1       0.02      1.00      0.03       439

avg / total       0.00      0.02      0.00     26005

[[    0 25566]
 [    0   439]]
*********************************************************
Cutoff = 0.01
             precision    recall  f1-score   support

    class 0       1.00      0.00      0.00     25566
    class 1       0.02      1.00      0.03       439

avg / total       0.98      0.02      0.00     26005

[[    3 25563]
 [    0   439]]
*********************************************************
Cutoff = 0.02
             precision    recall  f1-score   support

    class 0       1.00      0.21      0.35     25566
    class 1       0.02      0.98      0.04       439

avg / total       0.98      0.23      0.35     26005

[[ 5496 20070]
 [    7   432]]
*********************************************************
Cutoff = 0.03
             precision    recall 